<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.arkitik.flotale</groupId>
        <artifactId>flotale-core</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>flotale-core-task-initial</artifactId>
    <name>flotale-core-task-initial</name>

    <packaging>pom</packaging>
    <modules>
        <module>flotale-core-task-initial-entity-exposed</module>
        <module>flotale-core-task-initial-adapter-exposed</module>
        <module>flotale-core-task-initial-port-exposed</module>
        <module>flotale-core-task-initial-adapter</module>
        <module>flotale-core-task-initial-entity</module>
        <module>flotale-core-task-initial-domain</module>
        <module>flotale-core-task-initial-port-jpa</module>
        <module>flotale-core-task-initial-store</module>
    </modules>
</project>
