<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.arkitik.flotale</groupId>
        <artifactId>flotale-core</artifactId>
        <version>v1.0.0</version>
    </parent>
    <artifactId>flotale-core-element</artifactId>
    <name>flotale-core-element</name>

    <packaging>pom</packaging>
    <modules>
        <module>flotale-core-element-entity-exposed</module>
        <module>flotale-core-element-adapter-exposed</module>
        <module>flotale-core-element-port-exposed</module>
        <module>flotale-core-element-adapter</module>
        <module>flotale-core-element-entity</module>
        <module>flotale-core-element-domain</module>
        <module>flotale-core-element-port-jpa</module>
        <module>flotale-core-element-store</module>

    </modules>
</project>
