<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.arkitik.flotale</groupId>
        <artifactId>flotale-core</artifactId>
        <version>v1.0.0</version>
    </parent>
    <artifactId>flotale-core-workflow</artifactId>
    <name>${project.artifactId}</name>
    <packaging>pom</packaging>
    <modules>
        <module>flotale-core-workflow-adapter</module>
        <module>flotale-core-workflow-entity</module>
        <module>flotale-core-workflow-domain</module>
        <module>flotale-core-workflow-port-jpa</module>
        <module>flotale-core-workflow-store</module>
        <module>flotale-core-workflow-sdk</module>
        <module>flotale-core-workflow-operation</module>
        <module>flotale-core-workflow-port</module>
    </modules>
</project>
