<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.arkitik.flotale</groupId>
        <artifactId>flotale-core-element</artifactId>
        <version>v1.0.1</version>
    </parent>
    <artifactId>flotale-core-element-entity-exposed</artifactId>
    <name>flotale-core-element-entity-exposed</name>

    <dependencies>
        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-core-element-domain</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>io.arkitik.radix</groupId>
            <artifactId>radix-development-exposed-table</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.exposed</groupId>
            <artifactId>exposed-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.exposed</groupId>
            <artifactId>exposed-core</artifactId>
        </dependency>
        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-core-task-entity-exposed</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
    </dependencies>
</project>
