<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.arkitik.flotale</groupId>
        <artifactId>flotale-engine</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>flotale-engine-operation</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.arkitik.radix</groupId>
            <artifactId>radix-development-operation-ext</artifactId>
        </dependency>
        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-engine-sdk</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-core-action-sdk</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-core-element-sdk</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-core-stage-sdk</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-core-task-sdk</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-core-workflow-sdk</artifactId>
            <version>${project.parent.version}</version>
        </dependency>


        <dependency>
            <groupId>${project.parent.groupId}</groupId>
            <artifactId>flotale-engine-function</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
    </dependencies>

</project>
