<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.arkitik.flotale</groupId>
        <artifactId>flotale</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>flotale-engine</artifactId>
    <name>flotale-engine</name>

    <packaging>pom</packaging>
    <modules>
        <module>flotale-engine-core</module>
        <module>flotale-engine-workflow</module>
        <module>flotale-engine-stage</module>
        <module>flotale-engine-task</module>
        <module>flotale-engine-action</module>
        <module>flotale-engine-element</module>
    </modules>
</project>
